In [5]:
import numpy as np

In [6]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [7]:
np.array(my_list)

array([1, 2, 3])

In [8]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# arange

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

# zeros and ones

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# eye

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## random
# rand


In [18]:
np.random.rand(2)

array([0.43131616, 0.32856823])

In [19]:
np.random.rand(5,5)

array([[0.86037688, 0.3695819 , 0.75386233, 0.4017805 , 0.14436358],
       [0.38803928, 0.7172245 , 0.60754503, 0.10209804, 0.22968135],
       [0.48618296, 0.89070361, 0.77769923, 0.88996836, 0.98988848],
       [0.01088324, 0.05135743, 0.8302543 , 0.10716753, 0.36959586],
       [0.34998497, 0.72201061, 0.490548  , 0.21548812, 0.69866264]])

# randn

In [20]:
np.random.randn(2)

array([-2.60338641,  1.52097774])

In [22]:
np.random.rand(5,5)

array([[0.57504092, 0.08873396, 0.7511162 , 0.77003717, 0.75376558],
       [0.13746255, 0.86023044, 0.31507321, 0.52575204, 0.62039123],
       [0.26972795, 0.52801681, 0.64858601, 0.79427588, 0.40752782],
       [0.69377252, 0.37377486, 0.35057931, 0.1223343 , 0.31077571],
       [0.50329414, 0.74531276, 0.29971149, 0.2667257 , 0.85591401]])

# array attritbutes and methods

In [24]:
ranarr= np.random.randint(0,50,10)

In [25]:
ranarr.max()

39

In [26]:
ranarr.min()

0

In [28]:
ranarr.argmax()

2

In [29]:
ranarr.argmin()

5

# task

In [30]:
import numpy as np

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [41]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])